configfile: "workflow/config.yaml"

rule all:
    input:
        "data/processed/data_features.csv",
        "data/interim/make_dataset.csv",

rule prepare_datasets:
    input:
        "data/processed/data_features.csv",
    output:
        "data/processed/train.csv",
        "data/processed/valid.csv"
    shell:
        "python -m src.models.prepare_datasets {input} {output}"

rule build_features:
    input:
        "data/interim/make_dataset.csv"
    output:
        "data/processed/data_features.csv"
    shell:
        "python -m src.features.build_features {input} {output}"

rule make_dataset:
    input:
        "data/raw/train.csv",
        "data/raw/players_feats.csv"
    output:
        "data/interim/make_dataset.csv"
    shell:
        "python -m src.data.make_dataset {input[0]} {input[1]} {output}"
